imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        image_source_path: "%image_source_path%"
        image_helper: "@image_helper"
        category_helper: "@category_helper"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [AseagleBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port: 465
    encryption: ssl
    auth_mode: plain
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: WebPlatform\AseagleBundle\Entity\User
    service:
            mailer: fos_user.mailer.twig_swift
    registration:
            confirmation:
                enabled:    true
                from_email: # Use this node only if you don't want the global email address for the confirmation email
                                address: "noreply@aseagle.net"
                                sender_name: "Aseagle"
                template: AseagleBundle:EmailTemplates:confirmation.html.twig

sc_datetimepicker:
    picker: ~

recaptcha:
    public_key: "6Lct0gcTAAAAAG0w18ExgK81pQTwyQ2P9CKqi1Rt"
    private_key: "6Lct0gcTAAAAAF-VgIoyyVGMFC80y2GHI0e4YK30"
    use_https: false # optional

ewz_recaptcha:
    public_key: "6Lct0gcTAAAAAG0w18ExgK81pQTwyQ2P9CKqi1Rt"
    private_key: "6Lct0gcTAAAAAF-VgIoyyVGMFC80y2GHI0e4YK30"
    locale_key: "%kernel.default_locale%"
    enabled: true